version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/etc/redis/redis.conf:rw
    privileged: true
  nginx:
    image: nginx
    container_name: nginx
    privileged: true
    user: root
    ports:
      - 8888:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/html/php_nginx:/usr/share/nginx/html/php_nginx
      - ./nginx/html/vue_nginx:/usr/share/nginx/html/vue_nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/logs:/var/log/nginx:rw
  php-fpm:
    # image: php-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-fpm
    user: root
    privileged: true
    ports: 
      - 9000:9000
    volumes:
      - ./php/workspace:/app
      - ./php/php-fpm.conf:/etc/php7/php-fpm.conf:rw
      - ./php/php-fpm.d:/etc/php7/php-fpm.d:rw
  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - 8899:8080
    container_name: vue
    volumes:
      - ./vue/workspace:/workspace:rw
    tty: true
    stdin_open: true
