version: "3"
services:
  nginx:
    image: crazyjums/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 892:80
    tty: true
    volumes:
      - ./nginx/include:/usr/local/nginx/conf/include
      - ./nginx/html/php_nginx:/usr/local/nginx/html/php_nginx
      - ./nginx/html/vue_nginx:/usr/local/nginx/html/vue_nginx
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./nginx/logs:/data/nginx/logs:rw
    links:
      - "php-fpm"
    depends_on:
      - php-fpm
  php-fpm:
    image: crazyjums/php-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: always
    ports:
      - 9000:9000
    tty: true
    volumes:
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/php-fpm.d:/usr/local/php/etc/php-fpm.d
      - ./nginx/html/php_nginx:/app/php_nginx
  redis:
    image: redis
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/etc/redis/redis.conf:rw
    privileged: true
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:rw     #配置文件挂载到当前宿主机的/home/mysql/conf
      - ./mysql/data:/var/lib/mysql:rw            #数据挂载到当前宿主机的 /home/mysql/data
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=12345678