version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/etc/redis/redis.conf:rw
    privileged: true
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:rw     #配置文件挂载到当前宿主机的/home/mysql/conf
      - ./mysql/data:/var/lib/mysql:rw            #数据挂载到当前宿主机的 /home/mysql/data
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx/conf.d:/usr/local/nginx/conf/include
      - ./nginx/html/php_nginx:/usr/local/nginx/html/php_nginx
      - ./nginx/html/laravel_blog:/usr/local/nginx/html/laravel_blog
      - ./nginx/html/vue_nginx:/usr/local/nginx/html/vue_nginx
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./nginx/logs:/data/nginx/logs:rw
    depends_on:
      - php-fpm
    links:
      - "php-fpm"
  php-fpm:
    image: php-fpm
    # build:
    #   context: ./php
    #   dockerfile: Dockerfile
    container_name: php-fpm
    user: root
    privileged: true
    ports: 
      - 9000:9000
    volumes:
      - ./nginx/html/php_nginx:/app/php_nginx
      - ./nginx/html/laravel_blog:/app/laravel_blog
      - ./php/php-fpm.conf:/etc/php7/php-fpm.conf:rw
      - ./php/php-fpm.d:/etc/php7/php-fpm.d:rw
  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    image: vue_dev_nodejs_10_vuecli_4
    ports:
      - 8899:8080
    container_name: vue
    volumes:
      - ./vue/workspace:/workspace:rw
    tty: true
    stdin_open: true
